# SPDX-License-Identifier: GPL-2.0-only

obj-y	+= board.o
lwl-y	+= lowlevel.o
bbenv-y	+= defaultenv-saut-rk3568

clean-files	:= *.dtb *.dtb.S .*.dtc .*.pre .*.dts *.dtb.z
clean-files	+= *.dtbo *.dtbo.S .*.dtso
