#!/bin/sh

global.autoboot_timeout=2

usbgadget -d

# Get OTG ID pin state
gpio_get_value 10
state=$?

# Setup for host if zero
if [ $state -eq 0 ]; then
	otg.mode=host
	exit 0
fi

# Disallow wrong values
if [ $state -ne 1 ]; then
	echo "USB OTG port is in unknown state!"
	exit 1
fi

global.autoboot_timeout=10

if [ "$global.board.bootsource" = "serial" ]; then
	global.autoboot=abort
fi

#if [ -d /mnt/mmc0.1 ]; then
#	MS="-S"
#	global.system.partitions="/dev/mmc0.root(rootfs)"
#fi

#global.fastboot.partitions="/dev/mmc0(emmc)"
#usbgadget -a -A $MS

exit 0
