#!/bin/sh

if [ -f /mnt/mmc0.2/boot/Image.gz ]; then
	echo "Booting from MMC"

	global.bootm.image=/mnt/mmc0.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk0p3 ro rootdelay=3"

	DTB=/boot/rk3568-mg-evb.dtb
	if [ -f /mnt/mmc0.2$DTB ]; then
		echo "Using external devicetree blob from $DTB"
		global.bootm.oftree=/mnt/mmc0.2$DTB
	else
		echo "Using internal devicetree blob"
	fi

	exit 0
fi

exit 0
