#!/bin/sh

global.autoboot_timeout=2

if [ "$global.board.bootsource" = "usb" ]; then
	recover=1
	global.autoboot=abort
fi

if [ "$global.board.recovery" = "true" ]; then
	recover=1
	global.autoboot_timeout=10
fi

[ "$recover" = "1" ] || exit 0

global.fastboot.partitions="/dev/mmc1(emmc)"
usbgadget -a -A

exit 0
