#!/bin/sh

usbgadget -d

global.autoboot_timeout=2

if [ "$global.board.bootsource" = "usb" ]; then
	recover=1
	global.autoboot=abort
fi

if [ "$global.board.recovery" = "true" ]; then
	recover=1
	global.autoboot_timeout=10
fi

[ "$recover" = "1" ] || exit 0

if [ -d /mnt/mmc1.2 ]; then
	MS="-S"
	global.system.partitions="/dev/mmc1.root(rootfs)"
fi

global.fastboot.partitions="/dev/mmc1(emmc)"
usbgadget -a -A $MS

exit 0
