#!/bin/sh

if [ -f /mnt/mmc1.1/boot/Image.gz ]; then
	echo "Booting from SD"

	DTB=/mnt/mmc1.1/boot/imx8mm-diasom-evb.dtb

	global.bootm.image=/mnt/mmc1.1/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk1p2 ro rootdelay=3"
elif [ -f /mnt/mmc0.1/boot/Image.gz ]; then
	echo "Booting from eMMC"

	DTB=/mnt/mmc0.1/boot/imx8mm-diasom-evb.dtb

	global.bootm.image=/mnt/mmc0.1/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk0p2 ro rootdelay=3"
else
	echo "Boot image not found!"
	exit 1
fi

if [ -f $DTB ]; then
	echo "Using external devicetree blob from $DTB"
	global.bootm.oftree=$DTB
else
	echo "Using internal devicetree blob"
fi

exit 0
