#!/bin/sh

if [ -f /mnt/mmc1.1/boot/Image.gz ]; then
	echo "Booting from MMC"

	global.bootm.image=/mnt/mmc1.1/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk1p2 ro rootdelay=3"

	DTB=/boot/imx8mm-diasom-evb.dtb
	if [ -f /mnt/mmc1.1$DTB ]; then
		echo "Using external devicetree blob from $DTB"
		global.bootm.oftree=/mnt/mmc1.1$DTB
	else
		echo "Using internal devicetree blob"
	fi

	exit 0
fi

exit 0
