#!/bin/sh

if [ -f /mnt/mmc0.2/boot/Image.gz ]; then
	echo "Booting from SD"

	DTB=/mnt/mmc0.2/boot/rk3568-diasom-evb.dtb

	global.bootm.image=/mnt/mmc0.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk0p3 ro rootdelay=3"
elif [ -f /mnt/mmc1.2/boot/Image.gz ]; then
	echo "Booting from eMMC"

	DTB=/mnt/mmc1.2/boot/rk3568-diasom-evb.dtb

	global.bootm.image=/mnt/mmc1.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk1p3 ro rootdelay=3"
else
	echo "Boot image bot found!"
	exit 1
fi

if [ -f $DTB ]; then
	echo "Using external devicetree blob from $DTB"
	global.bootm.oftree=$DTB
else
	echo "Using internal devicetree blob"
fi

exit 0
