#!/bin/sh

DTB=/rk3568-diasom-evb.dtb
[ -f /mnt/mmc0.2$DTB ] || DTB=/boot/rk3568-diasom-evb.dtb

if [ -f /mnt/mmc0.2$DTB ]; then
	echo "Using external devicetree blob from $DTB"
	global.bootm.oftree=/mnt/mmc0.2$DTB
else
	echo "Using internal devicetree blob"
fi

if [ -f /mnt/mmc0.2/boot/Image.gz ]; then
	echo "Booting from SD"

	global.bootm.image=/mnt/mmc0.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk0p3 ro rootdelay=3"

elif [ -f /mnt/mmc1.2/boot/Image.gz ]; then
	echo "Booting from eMMC"

	global.bootm.image=/mnt/mmc1.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk1p3 ro rootdelay=3"

fi

exit 0
