# SPDX-License-Identifier: GPL-2.0-only

obj-y	+= board.o
lwl-y	+= lowlevel.o
bbenv-y	+= defaultenv-diasom-rk3568-evb
extra-y	+= rk3568-diasom-evb-lvds.dtbo
extra-y	+= rk3568-diasom-evb-test.dtbo

clean-files	:= *.dtb *.dtb.S .*.dtc .*.pre .*.dts *.dtb.z
clean-files	+= *.dtbo *.dtbo.S .*.dtso
